<a href="https://colab.research.google.com/github/vinaydonthojuaiml/vinay-pytorch/blob/main/Pytorch_Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Math Operations
# Add, Subtract, Multiply, Divide, Reminders, Exponents
#ShortHand and LongHand
#Reassignment







In [2]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([3,4,5,6])

#Addition
tensor_a+tensor_b

tensor([ 4,  6,  8, 10])

In [4]:
#Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 4,  6,  8, 10])

In [5]:
#Substraction
tensor_b - tensor_a


tensor([2, 2, 2, 2])

In [6]:
torch.sub(tensor_b,tensor_a)

tensor([2, 2, 2, 2])

In [7]:
#Multiplication
tensor_a *tensor_b

tensor([ 3,  8, 15, 24])

In [8]:
torch.mul(tensor_a,tensor_b)

tensor([ 3,  8, 15, 24])

In [9]:
#Division
tensor_b / tensor_a

tensor([3.0000, 2.0000, 1.6667, 1.5000])

In [10]:
torch.div(tensor_b,tensor_a)

tensor([3.0000, 2.0000, 1.6667, 1.5000])

In [11]:
#Reminder Modulus
tensor_b % tensor_a

tensor([0, 0, 2, 2])

In [14]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 2, 2])

In [15]:
#Exponenets / Power
torch.pow(tensor_b,tensor_a)

tensor([   3,   16,  125, 1296])

In [17]:
#Another way to write LongHand
tensor_a.add(tensor_b)

tensor([ 4,  6,  8, 10])

In [22]:
#Reassignment_
#tensor_a = tensor_a+tensor_b
tensor_a.add_(tensor_b)

tensor([10, 14, 18, 22])

In [23]:
tensor_a

tensor([10, 14, 18, 22])

In [25]:
tensor_a.sub_(tensor_b)

tensor([ 7, 10, 13, 16])

In [32]:
tensor_c = torch.tensor([1,2,3,4])
tensor_d = torch.tensor([2,3,4,5])
tensor_c
tensor_d
tensor_c.mul_(tensor_d)
#tensor_a.mul_(tensor_b)

tensor([ 2,  6, 12, 20])